# Generated by Django 5.2.10 on 2026-03-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_content',
            new_name='encrypted_for_recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_for_sender',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
