# Generated by Django 4.2.7 on 2026-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublickey',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpublickey',
            name='salt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
